server:
  port: 8081

spring:
  application:
    name: api-gateway

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

nats:
  url: nats://localhost:4222
  credsFile: "C:/nats-config/users/api-gateway.creds"