server.port: 8080
management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

nats:
  url: nats://localhost:4222

spring:
  config:
    import: optional:classpath:event-config.json

logging:
  level:
    org.springframework.boot:
      logging: DEBUG
      actuate: DEBUG
    com.sougata.natscore: TRACE
