server.port: 8080
management:
  endpoints.web.exposure.include: health,info
  endpoint:
    health:
      show-details: always

nats:
  url: nats://localhost:4222

spring:
  config:
    import: optional:classpath:event-config.json

logging:
  level:
    org.springframework.boot:
      logging: DEBUG
      actuate: DEBUG
    com.sougata.natscore: TRACE
