server:
  port: 8080

spring:
  application:
    name: api-gateway

nats:
  url: nats://localhost:4222

user:
  topics:
    create: user.create         # Function entry point for user creation
    response: user.response     # Function's reply target topic
    audit: user.audit           # Consumer topic for user events
    activity: user.activity     # Consumer topic for user activities
